apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: x240m5-13
  namespace: ocp-edge1
  labels:
    infraenvs.agent-install.openshift.io: ocp-edge1
spec:
  config:
    interfaces:
      - name: eno1
        macAddress: d4:f5:ef:40:82:00
    networkConfig:
      dns-resolver:
        config:
          server:
            - 10.46.57.1
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: d4:f5:ef:40:82:00
          ipv4:
            enabled: true
            dhcp: true
